### PR TITLE
Respect "Source positions" checkbox

### PR DESCRIPTION
**Pull request by hellux**

### CODE REVIEW

**Comment by matklad** [comment]
While we are at it, maybe disable it by default? Source positions add quite a bit of noise to html/ast outputs, and, at least for me, are rarely useful.

**Comment by jgm** [comment]
I enabled it by default in parsing because the scroll sync of the preview to the text depends on it.
At the very least, I'd like it to be enabled by default, but a few iterations ago I had it working so that the preview pane always got source positions but rendered versions didn't. That would be ideal.

**Comment by hellux** [comment]
Got it working I think, I got confused by the `sourcePositions` option to `djot.renderHTML`, though. It did not seem to have any effect, leftover from lua version?

Preview always has source positions now regardless of the checkbox state, and scroll sync thus always works.

**Comment by jgm** [comment]
Great, this makes sense.  Some of these were hangovers from the earlier Lua version.

**Pull request merged**
