### PR TITLE
renderDjot: adjust task_list indent to 6

### PR DESCRIPTION
**Pull request by black-desk**
Signed-off-by: black-desk <me@black-desk.cn>

### CODE REVIEW

**Comment by black-desk** [comment]
As order list is aligned after marker, I think task list should also be aligned after `- [X]`

**Comment by jgm** [comment]
Not sure what is best here. I'd be interested in comments from others. Choice is between

```
- [X] my list item
  wrapped.
```
and
```
- [X] my list item
      wrapped.
```

**Comment by jgm** [comment]
I think I prefer the 6 indent, so I'll merge this, but could reconsider.

**Comment by black-desk** [comment]
> I think I prefer the 6 indent, so I'll merge this, but could reconsider.

We could support some format options later.

**Pull request merged**
