### PR TITLE
Display a chechbox for checkboxes.

### PR DESCRIPTION
**Pull request by dcampbell24**
I am not very familiar with javascript, but I did my best to submit a valid change. I want to change the rust dependency jotdown, so I am submitting an upsteam change. I think you should display a checkbox for task items.

### CODE REVIEW

**Comment by jgm** [comment]
I think that if we do merge this, we might not want to include the class `checked` or `unchecked` on `li`. Reason: people currently use CSS with these to include a unicode checked or unchecked checkbox (see the sandbox for an example).  (And, with that CSS, a checkbox *does* display---it's just not one you can check or uncheck interactively.) After this change, using the same CSS would result in a doubled checkbox.

I think that using an input element as you do is the way it's currently done on GitHub and other places (e.g. pandoc), and it probably makes good sense.  Any thoughts @matklad ?

**Comment by matklad** [comment]
- The current behavior of using unicode symbols in HTML for checkboxes makes no sense to me, given HTML has checkboxes. So I am strongly in favor of merging something like this.
- I agree that we don't need `checked` and `unchecked` classes on `li` --- both because of compatibility argument, and because these are now redundant with checked state of the underlying input
- We need to keep the `task-list` class on the list itself (`ul`) --- this solution still requires custom CSS to remove the redundant list marker.

**Comment by jgm** [comment]
Thanks!

**Comment by KyleKing** [comment]
It would be great to have this change released to npm! I'm currently installing from GitHub locally because my markup heavily uses checkboxes

```bash
npx github:jgm/djot.js -f djot -t html docs/README.dj > public/README.html
```

**Comment by jgm** [comment]
Released 0.3.2.

**Pull request merged**
