### PR TITLE
renderDjot: omit auto generated attributes and reference

### LINKED ISSUE #69: Can we remove auto generated anchor in renderDjot output?
I am working on a lsp server for djot, and I want to use renderDjot as a formator.
Keep these anchors is werid.

### PR DESCRIPTION
**Pull request by black-desk**
Close #69

Signed-off-by: black-desk <me@black-desk.cn>

### CODE REVIEW

**Comment by jgm** [comment]
I think I like this plan, even though it makes the model a bit more complex.  It would be good to have some automated tests; it is a big change.

**Comment by black-desk** [comment]
I will add some tests few days later.

**Comment by black-desk** [comment]
pandoc.spec.ts seems already contains tests for attrs and references.

**Comment by black-desk** [comment]
@jgm done.

**Pull request merged**
